deploymentName: simple-web-deployment

replicaCount: 2

labels:
  app: simple-web

selectorLabels:
  app: simple-web

image:
  registry: acrinterview.azurecr.io
  repository: simple-web
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  name: default

service:
  name: simple-web-service
  type: ClusterIP
  port: 80
  targetPort: 8080
  portName: http
  protocol: TCP
  nodePort: null
  annotations: {}
  labels: {}
  selector: {}

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /amit
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

env: []