apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
    {{- with .Values.service.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.portName }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- if .Values.service.selector }}
{{ toYaml .Values.service.selector | indent 4 }}
    {{- else }}
{{ toYaml .Values.selectorLabels | indent 4 }}
    {{- end }}
